### ISSUE TITLE
The appveyor page with the nightly .zip file for Windows users is broken

### ISSUE THREAD

**Issue by erykwalczak** [pandoc-extras/pandoc-nightly#1]
The link in the README.md to the Windows nightly .zip file throws an error:
_An error occurred during a connection to ci.appveyor.com. Peer received a valid certificate, but access was denied. Error code: SSL_ERROR_ACCESS_DENIED_ALERT_

I tried go to the page directly but I get the same error. It seems like the page is not configured correctly. This could be a problem with appveyor but I thought it's worth letting you know.

**Comment by jgm** [comment]
This is because we changed the build location on appveyor, and starting building both 32 and 64 bit versions of the windows binaries.  I'm still unsure whether we'll continue this, but for now each build takes place in two environments, and the binaries are put in `windows\pandoc-windows-ARCH.msi/zip`, where ARCH is either `i386` or `x86_64`.

**Comment by jgm** [comment]
I've gone back to just building 32-bit versions for now, so this simplifies things.
The only change that should be necessary is a change in the path: instead of `windows\pandoc.msi`, it's now `windows\pandoc-windows-i386.msi`.
