### ISSUE TITLE
Question: pandoc-citeproc?

### ISSUE THREAD

**Issue by pdfkungfoo** [pandoc-extras/pandoc-nightly#5]
**Question:** Would it be reasonable and feasible to also build *pandoc-citeproc* and include it into the nightlies? Or does citeproc just not change that often?

**Comment by ickc** [comment]
It's a matter of practical issue: it is how pandoc-citeproc depends on pandoc (see [pandoc-citeproc's stack.yaml](https://github.com/jgm/pandoc-citeproc/blob/master/stack.yaml)). Looking at the [history there](https://github.com/jgm/pandoc-citeproc/blob/master/stack.yaml), it seems it isn't updated as often as pandoc's master. i.e. if one setup a nightly for pandoc-citeproc, the pandoc it bundles with will not be the latest pandoc master.

Since pandoc nightly's main purpose is for debug and quick testing new features and provide feedbacks, and most of them it is unrelated to pandoc-citeproc, it doesn't make much sense to provide 2 different nightly (one with pandoc only, with latest master, one with pandoc-citeproc and pandoc, with latest pandoc-citeproc and whichever commit of pandoc it depends on.)

However if one day pandoc-citeproc has much more active development that attracts many people wanting to test its new feature (or even new syntax) to provide feedback, then a pandoc-citeproc-nightly will make sense.
